name: Run unit tests

on:
  workflow_dispatch:
    inputs:
      fail-fast:
        type: boolean
        required: false
        default: true
  workflow_call:
    inputs:
      fail-fast:
        type: boolean
        required: false
        default: true

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: ${{ inputs.fail-fast }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email \
            "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - run: pip install poetry
      - run: pip install pynacl
      - run: |
          python -m unittest ${UNITTEST_ARGS}
        env:
          UNITTEST_ARGS: ${{ inputs.fail-fast && '-vf' || '-v' }}
          PYSEED_TEST_CREATE_PROJECT: 1
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
